// <auto-generated />
using System;
using ContorApa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContorApa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190530065842_DateAdded")]
    partial class DateAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContorApa.Models.ContorIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anul");

                    b.Property<int>("BaieCald");

                    b.Property<int>("BaieRece");

                    b.Property<int>("BucatarieCald");

                    b.Property<int>("BucatarieRece");

                    b.Property<DateTime>("DataInregistrarii");

                    b.Property<string>("Luna");

                    b.HasKey("Id");

                    b.ToTable("ContorIndexes");
                });
#pragma warning restore 612, 618
        }
    }
}
